### ISSUE TITLE
Reproduction of experimental results 

### ISSUE THREAD

**Issue by cgh2797** [clinfo/SBMolGen#2]
I ran the code on github as it is.

I ran the code in setting.yaml as it was in github,
An undruggable molecule has been created that is significantly different from the results of your paper.

How did you run setting.yaml when you tried to run the CDK2 example?

**Comment by biao-ma** [comment]
@cgh2797 Thank you for your report.
I can’t give you an exact answer because I have limited information and I don’t know exactly how it differs, but the following may be the cause:
1. Even with the same settings, ChemTS will generate different compounds each time because ChemTS (MCTS) is a stochastic algorithm.
2. If you retrained the RNN model, that may affect molecule generation. You may get better results if you use the original model parameters that have been uploaded.
Also, the way we run it is as I wrote on Github.

**Comment by charlesxu90** [comment]
Did you really use rDock? I didn't see the code where you run rDock in train_RNN.py or sbmolgen.py.

If you used, could you tell me in which line you call rDock to get a scoring function?

**Comment by cgh2797** [comment]
The example code written in how to use of README.md was executed as it is.
I installed rdock and confirmed that rdock is running.

As you said, there may be a problem with the interface between rdock and reinforcement learning.
I just executed the code you uploaded to github.

**Comment by charlesxu90** [comment]
Get it. Thanks! @biao-ma might know where it is called.

**Comment by biao-ma** [comment]
@charlesxu90 Please take a close look at the function "check_node_type"  in line 177 of sbmolgen.py for a clue to the use of rdock. 
You will notice that rdock_test_MP.py and add_node_type_zinc.py are related to rdock.

**Comment by charlesxu90** [comment]
Thanks a lot for the reply. I'll read it again.
